version: "3.9"

services:
  web:
    build: .
    container_name: snapdfy-invision
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./uploads:/app/uploads
      - ./static/reports:/app/static/reports
